Vamos a realizar diferentes procesos de reducción sobre los datos de las viviendas que hemos venido trabajando.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data=pd.read_excel('https://www.robertohincapie.com/data/datos_viviendas1.xlsx')
data.head()

,Cod_Inmueble,Barrio,Precio,Antiguedad,Area_Construida,Area_Privada,Valor_Admon,Parqueaderos,Habitaciones,Baños,Estrato
0,11318-M3058418,Castropol/Poblado,518000000,Entre 0 y 5 años,110.0,122.0,377000.0,1,4,3,6.0
1,11318-M3021864,Belen/Malibu,382000000,Entre 0 y 5 años,64.0,64.0,190000.0,1,2,3,5.0
2,11318-M3058231,Laureles,845000000,Entre 0 y 5 años,137.0,137.0,530000.0,2,3,4,5.0
3,13155-M3070155,EL POBLADO DE SANTA MARIA DE LOS ANGELES,705000000,Entre 0 y 5 años,123.0,123.0,600000.0,2,3,2,6.0
4,2364-M3070004,El Tesoro,1250000000,Remodelado,232.0,232.0,680000.0,2,3,5,6.0

In [ ]:
data['Precio']

0      518000000
1      382000000
2      845000000
3      705000000
4     1250000000
         ...
88     350000000
89     460000000
90     543000000
91     650000000
92    1350000000
Name: Precio, Length: 93, dtype: int64

In [ ]:
#Vamos a calcular algunos resultados de reducción de ciertas columnas del dataframe
print('Precio promedio: ',data['Precio'].mean()) #Acá utilizamos la función MEAN de pandas.
print('Precio promedio: ',np.mean(data['Precio'])) #Acá utilizamos la función MEAN de Numpy.

print('Precio máximo: ',data['Precio'].max())
print('Precio mínimo: ',data['Precio'].min())
print('Tercer cuartil, percentil del 75%', np.percentile(data['Precio'], 75))

Precio promedio:  726722580.6451613
Precio promedio:  726722580.6451613
Precio máximo:  2050000000
Precio mínimo:  176000000
Tercer cuartil, percentil del 75% 880000000.0